package me.statuxia.shulkerapi.model;

public enum BankCardHistoryType {

    CREATE_CARD,
    UPDATE_PIN,
    DISABLE_CARD,
    ENABLE_CARD,
    CHANGE_STYLE,

    DEPOSIT,
    WITHDRAW,
    TRANSFER_FROM,
    TRANSFER_TO,
    PAY_FINE,

    ADMIN_TRANSFER,

    UPDATE_NAME,

    UPDATE_GROUP_CARD_SETTING,
    ADD_GROUP_CARD_MEMBER,
    REMOVE_GROUP_CARD_MEMBER,
    UPDATE_GROUP_CARD_MEMBER_PIN,
    UPDATE_GROUP_CARD_MEMBER_SETTING
}
